// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: api/grpc/metrika.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BqConfig      *BqConfig      `protobuf:"bytes,1,opt,name=bqConfig,proto3" json:"bqConfig,omitempty"`
	CsConfig      *CsConfig      `protobuf:"bytes,2,opt,name=csConfig,proto3" json:"csConfig,omitempty"`
	MetrikaConfig *MetrikaConfig `protobuf:"bytes,3,opt,name=metrikaConfig,proto3" json:"metrikaConfig,omitempty"`
}

func (x *PushLogRequest) Reset() {
	*x = PushLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_metrika_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogRequest) ProtoMessage() {}

func (x *PushLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrika_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogRequest.ProtoReflect.Descriptor instead.
func (*PushLogRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrika_proto_rawDescGZIP(), []int{0}
}

func (x *PushLogRequest) GetBqConfig() *BqConfig {
	if x != nil {
		return x.BqConfig
	}
	return nil
}

func (x *PushLogRequest) GetCsConfig() *CsConfig {
	if x != nil {
		return x.CsConfig
	}
	return nil
}

func (x *PushLogRequest) GetMetrikaConfig() *MetrikaConfig {
	if x != nil {
		return x.MetrikaConfig
	}
	return nil
}

type PushLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PushLogResponse) Reset() {
	*x = PushLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_metrika_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogResponse) ProtoMessage() {}

func (x *PushLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrika_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogResponse.ProtoReflect.Descriptor instead.
func (*PushLogResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrika_proto_rawDescGZIP(), []int{1}
}

func (x *PushLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BqConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId  string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DatasetId  string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	TableId    string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	ServiceKey string `protobuf:"bytes,4,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"` // Название файла сервисного ключа
}

func (x *BqConfig) Reset() {
	*x = BqConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_metrika_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BqConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BqConfig) ProtoMessage() {}

func (x *BqConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrika_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BqConfig.ProtoReflect.Descriptor instead.
func (*BqConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrika_proto_rawDescGZIP(), []int{2}
}

func (x *BqConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *BqConfig) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *BqConfig) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *BqConfig) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

type CsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
}

func (x *CsConfig) Reset() {
	*x = CsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_metrika_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsConfig) ProtoMessage() {}

func (x *CsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrika_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsConfig.ProtoReflect.Descriptor instead.
func (*CsConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrika_proto_rawDescGZIP(), []int{3}
}

func (x *CsConfig) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type MetrikaConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YandexToken string  `protobuf:"bytes,1,opt,name=yandexToken,proto3" json:"yandexToken,omitempty"`
	CounterId   int64   `protobuf:"varint,2,opt,name=counterId,proto3" json:"counterId,omitempty"`
	Period      *Period `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
}

func (x *MetrikaConfig) Reset() {
	*x = MetrikaConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_metrika_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetrikaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetrikaConfig) ProtoMessage() {}

func (x *MetrikaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrika_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetrikaConfig.ProtoReflect.Descriptor instead.
func (*MetrikaConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrika_proto_rawDescGZIP(), []int{4}
}

func (x *MetrikaConfig) GetYandexToken() string {
	if x != nil {
		return x.YandexToken
	}
	return ""
}

func (x *MetrikaConfig) GetCounterId() int64 {
	if x != nil {
		return x.CounterId
	}
	return 0
}

func (x *MetrikaConfig) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

type Period struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateFrom string `protobuf:"bytes,1,opt,name=dateFrom,proto3" json:"dateFrom,omitempty"`
	DateTo   string `protobuf:"bytes,2,opt,name=dateTo,proto3" json:"dateTo,omitempty"`
}

func (x *Period) Reset() {
	*x = Period{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_metrika_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrika_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrika_proto_rawDescGZIP(), []int{5}
}

func (x *Period) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *Period) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type GetCountersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YandexToken string `protobuf:"bytes,1,opt,name=yandexToken,proto3" json:"yandexToken,omitempty"`
}

func (x *GetCountersRequest) Reset() {
	*x = GetCountersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_metrika_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountersRequest) ProtoMessage() {}

func (x *GetCountersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrika_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountersRequest.ProtoReflect.Descriptor instead.
func (*GetCountersRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrika_proto_rawDescGZIP(), []int{6}
}

func (x *GetCountersRequest) GetYandexToken() string {
	if x != nil {
		return x.YandexToken
	}
	return ""
}

type GetCountersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Counters string `protobuf:"bytes,1,opt,name=counters,proto3" json:"counters,omitempty"`
}

func (x *GetCountersResponse) Reset() {
	*x = GetCountersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_metrika_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountersResponse) ProtoMessage() {}

func (x *GetCountersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrika_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountersResponse.ProtoReflect.Descriptor instead.
func (*GetCountersResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrika_proto_rawDescGZIP(), []int{7}
}

func (x *GetCountersResponse) GetCounters() string {
	if x != nil {
		return x.Counters
	}
	return ""
}

var File_api_grpc_metrika_proto protoreflect.FileDescriptor

var file_api_grpc_metrika_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x6b, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b,
	0x61, 0x22, 0xac, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x62, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61,
	0x2e, 0x42, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x62, 0x71, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x2d, 0x0a, 0x08, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x2e,
	0x43, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x3c, 0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x6b, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x0d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x2b, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x84, 0x01,
	0x0a, 0x08, 0x42, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4b, 0x65, 0x79, 0x22, 0x2b, 0x0a, 0x08, 0x43, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x78, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x2e, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22, 0x3c, 0x0a, 0x06, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x22, 0x36, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x31, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x32, 0xe2, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x48,
	0x69, 0x74, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x12, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b,
	0x61, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x50, 0x75,
	0x73, 0x68, 0x56, 0x69, 0x73, 0x69, 0x74, 0x73, 0x54, 0x6f, 0x42, 0x51, 0x12, 0x17, 0x2e, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x48, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1b,
	0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x6b, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x6b, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_metrika_proto_rawDescOnce sync.Once
	file_api_grpc_metrika_proto_rawDescData = file_api_grpc_metrika_proto_rawDesc
)

func file_api_grpc_metrika_proto_rawDescGZIP() []byte {
	file_api_grpc_metrika_proto_rawDescOnce.Do(func() {
		file_api_grpc_metrika_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_metrika_proto_rawDescData)
	})
	return file_api_grpc_metrika_proto_rawDescData
}

var file_api_grpc_metrika_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_grpc_metrika_proto_goTypes = []interface{}{
	(*PushLogRequest)(nil),      // 0: metrika.PushLogRequest
	(*PushLogResponse)(nil),     // 1: metrika.PushLogResponse
	(*BqConfig)(nil),            // 2: metrika.BqConfig
	(*CsConfig)(nil),            // 3: metrika.CsConfig
	(*MetrikaConfig)(nil),       // 4: metrika.MetrikaConfig
	(*Period)(nil),              // 5: metrika.Period
	(*GetCountersRequest)(nil),  // 6: metrika.GetCountersRequest
	(*GetCountersResponse)(nil), // 7: metrika.GetCountersResponse
}
var file_api_grpc_metrika_proto_depIdxs = []int32{
	2, // 0: metrika.PushLogRequest.bqConfig:type_name -> metrika.BqConfig
	3, // 1: metrika.PushLogRequest.csConfig:type_name -> metrika.CsConfig
	4, // 2: metrika.PushLogRequest.metrikaConfig:type_name -> metrika.MetrikaConfig
	5, // 3: metrika.MetrikaConfig.period:type_name -> metrika.Period
	0, // 4: metrika.MetrikaService.PushHitsToBQ:input_type -> metrika.PushLogRequest
	0, // 5: metrika.MetrikaService.PushVisitsToBQ:input_type -> metrika.PushLogRequest
	6, // 6: metrika.MetrikaService.GetCounters:input_type -> metrika.GetCountersRequest
	1, // 7: metrika.MetrikaService.PushHitsToBQ:output_type -> metrika.PushLogResponse
	1, // 8: metrika.MetrikaService.PushVisitsToBQ:output_type -> metrika.PushLogResponse
	7, // 9: metrika.MetrikaService.GetCounters:output_type -> metrika.GetCountersResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_grpc_metrika_proto_init() }
func file_api_grpc_metrika_proto_init() {
	if File_api_grpc_metrika_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_metrika_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_metrika_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_metrika_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BqConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_metrika_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_metrika_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetrikaConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_metrika_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Period); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_metrika_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_metrika_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_metrika_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_metrika_proto_goTypes,
		DependencyIndexes: file_api_grpc_metrika_proto_depIdxs,
		MessageInfos:      file_api_grpc_metrika_proto_msgTypes,
	}.Build()
	File_api_grpc_metrika_proto = out.File
	file_api_grpc_metrika_proto_rawDesc = nil
	file_api_grpc_metrika_proto_goTypes = nil
	file_api_grpc_metrika_proto_depIdxs = nil
}
